### ISSUE TITLE
Time stamp differences

### ISSUE THREAD

**Issue by danhey** [afeinstein20/eleanor#119]
Hi all, thanks for the great package.

We've been using Eleanor to extract LCs of some stars, and found that the exact time stamps don't seem to match up with LCs from TASOC. In particular, the differences in time stamps appears to fluctuate between 1798.25 s and 1803.5 s.

I've plotted this below for the star TIC 167303881 in sector 1. Every 3 cadences, the time difference changes by 5 s. This is different to what the same LC in TASOC returns. 

![eleanor_what](https://user-images.githubusercontent.com/38233719/64234953-b435fa80-cf3a-11e9-86ce-b40483ead739.png)

Here is the code I use for Eleanor;
```python
star = eleanor.Source(tic=167303881, sector=1, tc=True)
data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True)
diff = np.diff(data.time)
```

Cheers!
Dan

**Comment by ethankruse** [comment]
Ohhhh boy this one's fun. So I've spent 2 hours looking into this because I love a good computer science mystery hunt.

Here's what I've gathered: this is a floating point bug and definitely worth fixing in eleanor.

Long story short, if you represent a value as a 32-bit floating point, you only get ~8 decimal places of precision (2^23 different values to be precise). So when times are in the thousands (1596.77316...), representing it as a float32 means the precision stops around the 4th decimal place, 0.0001 days, or 10 seconds, as you found. **So none of the eleanor time stamps can possibly be more accurate than to the nearest 10 seconds.**

This should probably be fixed. It's an easy, one line fix to the eleanor-tools package that I just submitted.

**Comment by benmontet** [comment]
Thank you to both of you! I have good news and bad news.

The good news: I agree with Ethan's assessment as to what's causing this. Your proposed fix for eleanor-tools looks correct to me. That should give the times the correct precision in the postcards.

The bad news: Dan, in your example you passed through `tc=True`, so it uses TessCut to build a postcard rather than using one of our own, so Ethan's fix won't affect your workflow. In fact, this error is coming from TessCut itself---they seem to have exactly the same bug we do. I downloaded a TessCut frame for this star for sector 1 and plotted the difference in seconds between consecutive cadences, without eleanor in my workflow at all. Guess what? Time series below:

![image](https://user-images.githubusercontent.com/1314530/64305529-4cd97400-cf55-11e9-943d-fd1d4a01bf41.png)

So we need TessCut to fix something on their end, too.

TESS must be saving things behind the scenes as a 64 bit float otherwise the TASOC light curves would have the same issue, right? So this is a temporary thing that will just be propagated through to the eleanor data products once the TessCut frames are fixed.

I'll ping them now!

Thank you both for bringing this up and sleuthing!

**Comment by timbedding** [comment]
you're welcome!  The TASOC light curve does not have this issue (I checked).  We were looking at this because I wanted to see the size of the barycentric corrections.  I guess it won't matter much for most applicaitons but it would be nice to fix it :-)

**Comment by ethankruse** [comment]
Ah good point on the TESSCut thing. I can confirm that timing precision is stored at 64 bits in all the official TESS products, including FFIs and short cadence light curves, and that running the differences gives the same answer every time with them.

The exception is in the barycentric corrections, which are 32 bit as I noted in the eleanor-tools PR. That's because those all start 0.000XXX and so the 8 decimal places of precision gets you to the 11th decimal in that case, which is at the microsecond level.

**Comment by benmontet** [comment]
The TESSCut issues still seem to exist (I've put in a pull request over there and communicated this issue with them through other channels as well) but the eleanor postcards (with tc=False) give times to 64 bit precision, so this will work as expected from v1.0.0! Thank you all for pointing this out!
