### ISSUE TITLE
Bug in eleanor.targetData()

### ISSUE THREAD

**Issue by IsabelLipartito** [afeinstein20/eleanor#132]
Hi everyone, thank you for this great code!

I'm trying to create light curves for a few targets and I am running into an issue with collecting target data for three of these targets.  

`ms = eleanor.multi_sectors(coords=SkyCoord(119.83224, -60.57880, unit="deg")  , sectors='all', tc=True)`

`sector1=eleanor.TargetData(ms[0])`

I get this warning:  

`WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped. [astropy.stats.sigma_clipping]`

and then a traceback error from self.get_lightcurve() that seems to indicate that there is no data available from sector 1, even though it originally printed:  'Found star in Sector(s) 1 4 7 8 9 10'.  I copied the traceback error at the very end.  This only happened for sector 1, the others returned the light curve just fine.

I am getting TESS light curves for 70 stars, and this only happened for 3 of these stars: coordinates [(119.83224, -60.57880), (119.82105, -60.57037), (119.68231, -60.54910)]

Best,

Isabel

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-129-6b416c310dbf> in <module>
----> 1 sector1=eleanor.TargetData(ms[0])

~/anaconda3/envs/ocs3/lib/python3.7/site-packages/eleanor/targetdata.py in __init__(self, source, height, width, save_postcard, do_pca, do_psf, bkg_size, crowded_field, cal_cadences, try_load)
    197                 self.create_apertures(height, width)
    198 
--> 199                 self.get_lightcurve()
    200 
    201                 if do_pca == True:

~/anaconda3/envs/ocs3/lib/python3.7/site-packages/eleanor/targetdata.py in get_lightcurve(self, aperture)
    497                 lc_obj_tpf = lightcurve.LightCurve(time = self.time[q][self.cal_cadences[0]:self.cal_cadences[1]],
    498                                        flux = all_corr_lc_tpf_sub[a][q][self.cal_cadences[0]:self.cal_cadences[1]])
--> 499                 flat_lc_tpf = lc_obj_tpf.flatten(polyorder=2, window_length=51)
    500 
    501                 tpf_stds[a] =  np.std(flat_lc_tpf.flux)

~/anaconda3/envs/ocs3/lib/python3.7/site-packages/lightkurve/lightcurve.py in flatten(self, window_length, polyorder, return_trend, break_tolerance, niters, sigma, mask, **kwargs)
    486             mask1 = np.nan_to_num(np.abs(self.flux[mask] - trend_signal)) <\
    487                     (np.nanstd(self.flux[mask] - trend_signal) * sigma)
--> 488             f = interp1d(self.time[mask][mask1], trend_signal[mask1], fill_value='extrapolate')
    489             trend_signal = f(self.time)
    490             mask[mask] &= mask1

~/anaconda3/envs/ocs3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in __init__(self, x, y, kind, axis, copy, bounds_error, fill_value, assume_sorted)
    466         # Interpolation goes internally along the first axis
    467         self.y = y
--> 468         self._y = self._reshape_yi(self.y)
    469         self.x = x
    470         del y, x  # clean up namespace to prevent misuse; use attributes

~/anaconda3/envs/ocs3/lib/python3.7/site-packages/scipy/interpolate/polyint.py in _reshape_yi(self, yi, check)
    109                                            self._y_extra_shape[:-self._y_axis])
    110             raise ValueError("Data must be of shape %s" % ok_shape)
--> 111         return yi.reshape((yi.shape[0], -1))
    112 
    113     def _set_yi(self, yi, xi=None, axis=None):

ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

**Comment by benmontet** [comment]
Hi @IsabelLipartito,

Thanks for posting this! I am able to reproduce the error.

The issue here was a bug on our part that only appears when the star falls right on the edge of the detector. I ran these three stars all through tess-point and one thing they all have in common is in sector 1 they fall within 2.5 pixels of the edge of the detector.

I've squashed our bug, and if you download the now-current version on github you should get results (and still the same warning about clipping nans, which are nan because they're positions of where pixels off the edge of the detector would be). These will flow through to the next pip version when that is next updated, typically when the new sector of data is released.

I'll warn you to be especially cautious of stars right on the edge, both in K2 and TESS we get much worse photometry in these cases because small changes in pointing of the telescope affect how much of the starlight lands on the detector, leading to much worse pointing based systematics than for stars not on the edges. You might need to do more sophisticated pointing-based systematics removal, or consider using PSF fitting (which does a better job at the edges because the PSF stays the same shape even as part of the star falls off the detector) for these specific cases.

If updating your eleanor to the current github version solves your issue please close it, otherwise if you're still getting errors let us know and I can dig in further and try to figure out why.

Good luck!

**Comment by IsabelLipartito** [comment]
Thank you- I reinstalled the pipeline and the bug is fixed.  I'll pay attention to these stars- thank you for the information about the telescope pointing.

Best,

Isabel
