### ISSUE TITLE
Sector 14 metadata directory is missing the CBV files

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#139]
This is the only sector with this problem, seems like it should be a pretty easy fix.

**Comment by benmontet** [comment]
As eleanor doesn't try to read these in, but rather creates them the first time a target is made for a sector, I've removed the metadata files for s0014 and onward, which should then resolve this issue, in a sense. Having them inside the eleanor directory is a callback anyway, they would never be used in that spot since we've moved their location to ~/.eleanor! So these were just excess files that a local installation of eleanor no longer interacted with.

@afeinstein20 is there any reason we should be keeping any of the eleanor/metadata subdirectories in here? eleanor/metadata/ffi.guide is essential but I think all of the eleanor/metadata/s00*/* files are never used. Is that correct? And if so can we delete them? I don't want to accidentally remove actually-necessary files!

**Comment by afeinstein20** [comment]
The subdirectories were removed a few weeks ago I thought? And we certainly don't use the guide anymore, so I think we're good on this front!

**Comment by benmontet** [comment]
They were removed from the pip version but have been hanging out in the github one still. 

The big guide is gone but we still have a file called ffi.guide which is the locations of postcards in pixel coordinates on a chip. That one we still use! I'll go ahead and remove the other directories then.
