### ISSUE TITLE
Issue with multi_sector

### ISSUE THREAD

**Issue by rachelbf** [afeinstein20/eleanor#143]
I have been using eleanor to get multi sector light curves and up until a couple days ago, had no issues. Not sure why this error popped up.

<img width="1362" alt="Screen Shot 2020-01-13 at 15 13 09" src="https://user-images.githubusercontent.com/48811452/72300017-77c88880-3617-11ea-8421-6bcf8ef7417e.png">

**Comment by benmontet** [comment]
Try pulling the latest version on github, I think I found the bug that was causing this (we were initializing self.tess_mag as an integer rather than a list in certain cases). If you use the github version it should handle this properly now; the next pip version will handle it properly as well once that gets upgraded to v1.0.2---probably in the next few days. I'm going to close this issue because I think it's sorted; if I'm wrong and this issue continues to pop up after you install the latest version please re-open it!
