### ISSUE TITLE
Postcard centers bug

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#153]
The postcard_centers.txt needs to be updated with the actual centers of the postcards. More specifically, all the x-centers that are currently 2078 need to be changed to 2018 to reflect the postcards as made.

Minimum working example:
`star = eleanor.Source(tic=89465072, sector=1)`

That TIC has in fact been observed (web viewing tool says so, MAST says so), but eleanor fails and defaults to TESSCut (which does work). The reason: if you put in a 
```
print(self.postcard)
print(self.all_postcards)
```
into Source, just before the MAST call (~line 332), you'll get 
```
postcard-s0001-1-1-cal-2078-1996
['postcard-s0001-1-1-cal-1980-1888' 'postcard-s0001-1-1-cal-1980-1942'
 'postcard-s0001-1-1-cal-1980-1996' 'postcard-s0001-1-1-cal-2078-1888'
 'postcard-s0001-1-1-cal-2078-1942' 'postcard-s0001-1-1-cal-2078-1996']
```
So it believes the closest postcard is `postcard-s0001-1-1-cal-2078-1996`, and it goes off to MAST to find it and comes back saying it doesn't exist, because it doesn't. eleanor-tools changes that last postcard to have a center of 2018, not 2078. If you change the postcard_centers.txt file from 2078 -> 2018, then eleanor with the MAST postcards works and creates a nice light curve.

Was this intentional and just a bug/forgetful moment in creating the postcard centers file or does this mean eleanor actually doesn't have coverage of the last 60 pixels of the detector when it's supposed to?

**Comment by benmontet** [comment]
Yep, this was a bug. The postcards form a uniformly spaced grid, except for one right at the end because the differential between postcard centers isn't equally divisible by the width of the detector. The last one is centered at 2018, not 2078 and the wrong number got input into that file. I've updated it now. Thanks!

Also added in the change to the load_pointing_model call in ffi.py from #149
