### ISSUE TITLE
Custom aperture using the default aperture provides a different light curve than the default light curve.

### ISSUE THREAD

**Issue by dinilbose** [afeinstein20/eleanor#158]
The default aperture for calculation of light curve from the eleanor package is extracted and provided as custom aperture. The light curve obtained from both of them seems to be different. Typically there should not be any change in the light curve since default and custom apertures are the same. We here provide two examples of this situation. In the first example, Wasp-100 shows a slight variation in the flux when default and custom apertures are compared. But in the second example, the flux variation seems to be quiet large. I am attaching the python notebook for showing the entire process. Please have look and let me know what I am missing?

[https://github.com/dinilbose/issue/blob/master/Issue_eleanor_flux.ipynb](https://github.com/dinilbose/issue/blob/master/Issue_eleanor_flux.ipynb)

**Comment by benmontet** [comment]
Thanks for raising this issue! This is definitely a bug in the code.

When you use TargetData(), behind the scenes the code tests a few different apertures and also a few different background models. You can see what it selects by printing data.bkg_type. When you pass in the custom aperture, it doesn't test the different background models and only uses the simplest one (which is the oldest one we had...this piece of the code was written when we had only one background model), so you're getting returned a sub-optimal background model, which is why the discrepancy is largest when the background is largest.

We'll straighten this out in the next few days and let you know when we do.

@afeinstein20 I propose the following: someone should be able to pass a ```bkg_type``` into custom aperture. If they do, it should use that directly, and if they don't it should test all three and return the lowest cdpp one. We should have all the code written for that already, it's just changing around the logic. Does that seem sensible to you? Or do you have a better approach in mind?

**Comment by benmontet** [comment]
Thanks again for pointing this out, I've re-written the logic of this function and it should now work properly. Running your example notebook now gives the expected result, that the two paths give the same light curve.

You can get the latest version on github right now, and the next release on Pypi will also include this fix.

I'm going to close the issue, if it's still not working for you feel free to reopen it!
