### ISSUE TITLE
Targets that fall in multiple sectors

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#16]
Simple ways to find when a star falls in multiple sectors (this will be a TESS GI tool possibly?) and stitch these together

**Comment by megbedell** [comment]
I think this requires minimal rewriting in Source (just have to try to find the source in every sector instead of breaking after locating it once, and keep a list of best postcards/positions rather than a single one). The part I'm less clear on is how, structurally, we want to save the TPFs and light curves from each sector in TargetData - as lists with an additional attribute that's a same-length list consisting of sector index? What's the standard for different Kepler quarters in lightkurve?

**Comment by benmontet** [comment]
I agree with @megbedell's general sentiment; we should have a broader conversation about whether or not this is a part of ellie. In Kepler/K2 land, there is a separate file for each quarter, and then tools to combine them ex post facto, through things like kplr or lightkurve.
