### ISSUE TITLE
No data for star which has data

### ISSUE THREAD

**Issue by hippke** [afeinstein20/eleanor#168]
I use eleanor version 1.0.3 with Python 3.7 and try to obtain a light curve for a star with coordinates. Minimal example:

```
import numpy as np
import eleanor
from astropy import units as u
from astropy.coordinates import SkyCoord
print(eleanor.__version__)
coords = SkyCoord(ra="00:00:16.37", dec="-72:46:43.5", unit=(u.deg, u.deg))
star = eleanor.Source(coords=coords)
data = eleanor.TargetData(star, do_pca=True)
```
Results in an error message:
```
1.0.3
INFO: Found cached file /home/michael/.eleanor/mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0001-3-2-cal-1000-1348_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0001-3-2-cal-1000-1348_tess_v2_bkg.fits with expected size 78955200. [astroquery.query]
INFO: Found cached file /home/michael/.eleanor/mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0001-3-2-cal-1000-1348_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0001-3-2-cal-1000-1348_tess_v2_pc.fits with expected size 158022720. [astroquery.query]
INFO: Found cached file /home/michael/.eleanor/mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0001-3-2-cal-1000-1348_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0001-3-2_tess_v2_pm.txt with expected size 238335. [astroquery.query]
WARNING: FITSFixedWarning: 'datfix' made the change 'Set MJD-OBS to 58324.815286 from DATE-OBS.
Set DATE-BEG to '2018-07-25T19:35:09.893' from MJD-BEG'. [astropy.wcs.wcs]
/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/targetdata.py:336: UserWarning: The size postage stamp you are requesting falls off the edge of the postcard.
  warnings.warn("The size postage stamp you are requesting falls off the edge of the postcard.")
/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/targetdata.py:337: UserWarning: WARNING: Your postage stamp may not be centered.
  warnings.warn("WARNING: Your postage stamp may not be centered.")
/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/numpy/ma/core.py:5159: RuntimeWarning: Mean of empty slice.
  dtype=dtype, **kwargs)[()]
/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "/home/michael/Desktop/temp_tess/debug_eleanor.py", line 9, in <module>
    data = eleanor.TargetData(star, do_pca=True)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/targetdata.py", line 204, in __init__
    self.get_tpf_from_postcard(source.coords, source.postcard, height, width, bkg_size, save_postcard, source)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/targetdata.py", line 369, in get_tpf_from_postcard
    mpix = np.unravel_index(summed_tpf.argmax(), summed_tpf.shape)
ValueError: attempt to get argmax of an empty sequence
```

**Comment by bsipocz** [comment]
@hippke - naively (as I don't know much about eleanor internals as such) I would suggest to try to get rid of the cache first. E.g. all from /home/michael/.eleanor/mastDownload, and then try again.

Another question is the version number of packages you use. E.g. astropy, astroquery, numpy and eleanor. There hasn't been relevant looking changes lately in astroquery, but nevertheless make sure you have the latest version of it (0.4, or even better a 0.4.1.dev prerelease, installable with `pip --pre -U astroquery`)

**Comment by benmontet** [comment]
I agree with @bsipocz that it would be good to know what versions you are using! Some similar issues we've run into have been solved by moving to astropy >=4.0/astroquery >=0.4. If you are using older versions than either of those I would upgrade and try again!

Also this won't cause this issue but I have a feeling the units to your SkyCoord entry should be ```unit=(u.hourangle, u.deg))```. This won't affect your ability to make a light curve since the RA is so close to zero both are in the same sector (and even fall on the same postcard), but one of these apertures looks much more interesting than the other 😉

**Comment by hippke** [comment]
@bsipocz Thank you! Clearing the cache solved it. Packages were all up to date.
@benmontet Thank you, indeed the coordinate units were wrong in addition.

Is it a common thing that updates of eleanor require clearing the cache? I hadn't used and updated eleanor it in a few months. If cached data are incompatible with current the version, should we raise a warning/error?

**Comment by benmontet** [comment]
Great, I'm going to close the issue in that case!

It is uncommon for updates to require clearing the cache. The exception is moving from <1.0 versions to >=1.0; that version change made many large and not-backward-compatible changes to the way data storage is done like you might expect from a major version number roll. That upgrade happened just before the New Year, so if you haven't updated in a few months you probably crossed it. Because it's just that one boundary I don't think we need a warning/error, but it probably will be good to include this in the docs. I've been talking a big game recently about re-writing the tutorials and I think I'm actually going to get to do it this coming week! That would be a good place to include this.
