### ISSUE TITLE
Add ability to only store tesscut fits files transiently

### ISSUE THREAD

**Issue by hposborn** [afeinstein20/eleanor#170]
I was running a script which occasionally uses Eleanor to create TESS lightcurves, but within two hours it had hit the 100GB limit on the server almost exclusively because of those tesscut fits files, which are obviously >25x the size of the extracted lightcurves.

I can just periodically rm -r in the .eleanor/mastDownload directory for the moment. But if it is possible to include a feature which would turn off the storage of those big files in the future - either putting them in a temporary folder, directly storing the downloaded file in memory/cache, or simply deleting after use - I would very much like to request it.

**Comment by benmontet** [comment]
When you call eleanor.TargetData(), you can pass through a Boolean argument ```save_postcard```. If that is false, it will delete the downloaded postcard (here the TESScut fits file) when it's done making everything.

That certainly works for the standard postcards when tc=False, if it's not working properly with tesscut frames let us know because then there's surely a bug in the system somewhere!

**Comment by hposborn** [comment]
Oh, amazing! I searched the docs for something like that, but obviously not hard enough. Thanks
