### ISSUE TITLE
Cannot download sector 22 data

### ISSUE THREAD

**Issue by michaelcarini** [afeinstein20/eleanor#176]
I have been trying to produce light curves for sources in Sector 22. ELEANOR keeps claiming "TESS has not (yet) observed your object". I have checked, all my packages are up to date. I have tried to download the sector metadata first-that works, but I still cannot get ELEANOR to donwload the target. I am running on a MAC OSX 10.13.2

**Comment by benmontet** [comment]
Hi Michael,

Does this same issue occur for all sources you try in that sector?

How did you download the metadata? By running eleanor.Update() or doing something different?

One of the things that update.py should do in addition to grabbing all the metadata is update a file called maxsector.py located in your eleanor directory (if you're not sure where this is, you can `print(eleanor.__path__)`). Your error sounds like the behavior if that file isn't updated during an update for some reason. If the variable in there is less than 22, or 23 now that the newest sector is out, can you manually update that file and try again?

**Comment by michaelcarini** [comment]
Thank you for the quick response.
Yes, I used Eleanor.Update() to update the metadata.
Maxsector was 22, I tried changing it to 23-still no luck with sector 22 data.
Happens with any object I try in sector 22.
I can retrieve objects in sector 21.

Michael

**Comment by benmontet** [comment]
Weird! Okay, can you please run the following from the command line and let me know the output?

`python -m tess_stars2px -t NNNNNNNN'

where NNNNNNNN is the TIC ID of one of your objects. 

Can you then also run exactly the same command with TIC ID 198237770 and copy the output of that, too?

This is calling the tess-point module we use to identify which sectors an object has been observed for. The output of this will help differentiate where in eleanor the issue is arising, whether it's not finding the right object in the first place or is finding the right object but then doing something improper with it.

**Comment by michaelcarini** [comment]
Here you go-I actually ran it for two different sector 22 targets.
I guess I should have also mentioned I was running in a Jupyter notebook.
Michael
[cid:image001.png@01D62FAD.D6534F40]

**Comment by benmontet** [comment]
Hi Michael,

The image didn't come through, it just shows as 

[cid:image001.png@01D62FAD.D6534F40]

github strips the html when you respond through the email so can you either please post it to the github issue page or email it to me directly (b.montet AT unsw.edu.au) rather than through github?

Thanks!

**Comment by benmontet** [comment]
For future readers possibly facing this same issue: update your maxsector.py file and also reload the module; if you're working in a notebook for example the code won't notice the change until you re-import eleanor.
