### ISSUE TITLE
Tess Flux to Tess Magnitude.

### ISSUE THREAD

**Issue by AstroNeel98** [afeinstein20/eleanor#181]
Eleanor gives us light curves which show the variation in flux, on the vertical axis. Is it possible to obtain light curves which plot the variation in magnitude instead of flux for our source ?

**Comment by benmontet** [comment]
eleanor does not do the conversion to magnitudes, but you can convert relative fluxes to relative magnitudes using the standard relation that defines magnitudes.

Converting to absolute (rather than relative) magnitudes can be done using information in the TESS handbook about the flux/magnitude zeropoint, but note you will need to understand both the amount of light from the star that is in/out of your aperture as well as the contamination from nearby background sources.
