### ISSUE TITLE
eleanor.update.Update() downloads tesscut files to working directory

### ISSUE THREAD

**Issue by baileyji** [afeinstein20/eleanor#212]
Hi Folks, I was on v0.2.8 without problems and just migrated to v2.01 (4a94324) via  what pip pulled down for a new conda environment. It looks like eleanor.source.Source calls download_tesscut with path set to .eleanor/tesscut but eleanor.update.Update calls Tesscut.download_cutouts without specifying a path resulting in the working directory being gunkified. adding a path= call to the same directory as in source.py seems to fix this. Some other portion of the process is also filling the working directory with files but it does seem to delete those automatically (provided one doesn't kill the interpreter!).

**Comment by benmontet** [comment]
That file isn't needed long-term, just to make some of the metadata products, so I did you one better, it should now get automatically deleted once it's done being used. 

You're correct about those other files, they are used by `eleanor` behind the scenes so they get moved at the end to the `~/.eleanor/metadata` directory as long as nothing breaks along the way while they're being made. 

The github version is now updated to reflect this, so you can download that directly right now if you'd like, and this will flow through to the pip version the next time we do a version update so I'm going to close this because I believe it's sorted; if you're still having issues do feel free to reopen or to open a new issue.
