### ISSUE TITLE
Maxsector updates

### ISSUE THREAD

**Issue by martindevora** [afeinstein20/eleanor#217]
Hi, I was wondering how is the maxsector.py file update. Does it require Eleanor to launch a new release every time the maxsector is updated? If not, I would like to know how it is dynamically updated.

Kind regards,
Martín.

**Comment by benmontet** [comment]
Hey,

It shouldn't require an update for each new sector. It's dynamically updated when eleanor.Update() is called, in the `try_next_sector()` function. In short, it opens maxsector.py at the end of the update, checks the current maxsector value, and (assuming the update ran successfully) then updates maxsector so eleanor knows what data is available to try to download from MAST and produce light curves for.

We chose to do it this way (it is admittedly a bit of a hack) because we use `tess-point` behind the scenes to figure out what area of the detector to download at light curve creation time. `tess-point` returns information up to sector 55, but not information about what's actually been observed, and we wanted the user who calls `eleanor.source.multi_sectors` to be able to get the data for all sectors the star is observed in without needing to know that information without looping over many sectors, giving queries to MAST to downlink data that doesn't exist and getting errors back (that are pretty time-consuming, so we'd like to avoid even doing the query). A quick hack that tells it to downselect only to sectors less than MAXSECTOR makes it more efficient for people doing large batches of light curve creation, and hopefully the update works as intended on all architectures!
