### ISSUE TITLE
Windows 10 Permission + OS Errors

### ISSUE THREAD

**Issue by AlexanderEvitt** [afeinstein20/eleanor#219]
I'm running eleanor 2.0.1, cloned from GitHub yesterday, with all the required dependencies on python 3.7.3 on a Windows 10 computer. It looks like there are some problems with how eleanor runs on Windows machines. When fitsio was dropped as a dependency, that allowed older versions of eleanor to work on my computer, but since updating things have been broken. 
For example, if I import eleanor and call:

`star = eleanor.multi_sectors(sectors='all',tic=0,gaia=gaia,coords=(ra,dec),tc=True)`

I get an OSError:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-1756b4bd6905> in <module>
      8 full_lc = lk.LightCurve([],[])
      9 for observation in star:
---> 10     data = eleanor.TargetData(observation,bkg_size=5)
     11     #data.custom_aperture(shape='rectangle', h=1,w=1, method='exact')
     12     #data.get_lightcurve()

~\anaconda3\envs\lightcurve\lib\site-packages\eleanor-2.0.1-py3.7.egg\eleanor\targetdata.py in __init__(self, source, height, width, save_postcard, do_pca, do_psf, bkg_size, aperture_mode, cal_cadences, try_load, regressors, language)
    184                     self.post_obj = Postcard_tesscut(source.cutout)
    185 
--> 186                 self.ffiindex = self.post_obj.ffiindex
    187                 self.flux_bkg = self.post_obj.bkg
    188                 self.get_time(source.coords)

~\anaconda3\envs\lightcurve\lib\site-packages\eleanor-2.0.1-py3.7.egg\eleanor\postcard.py in ffiindex(self)
    349         sector = self.header['SECTOR']
    350         eleanorpath = os.path.join(os.path.expanduser('~'), '.eleanor')
--> 351         A = np.loadtxt(eleanorpath + '/metadata/s{0:04d}/cadences_s{0:04d}.txt'.format(sector))
    352         return A
    353 

~\anaconda3\envs\lightcurve\lib\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
    959             fname = os_fspath(fname)
    960         if _is_string_like(fname):
--> 961             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
    962             fencoding = getattr(fh, 'encoding', 'latin1')
    963             fh = iter(fh)

~\anaconda3\envs\lightcurve\lib\site-packages\numpy\lib\_datasource.py in open(path, mode, destpath, encoding, newline)
    193 
    194     ds = DataSource(destpath)
--> 195     return ds.open(path, mode, encoding=encoding, newline=newline)
    196 
    197 

~\anaconda3\envs\lightcurve\lib\site-packages\numpy\lib\_datasource.py in open(self, path, mode, encoding, newline)
    533                                       encoding=encoding, newline=newline)
    534         else:
--> 535             raise IOError("%s not found." % path)
    536 
    537 


OSError: C:\Users\abcmo\.eleanor/metadata/s0002/cadences_s0002.txt not found.
```

Now, I think that this might be due to the file path shown in the error. Having backslashes and forward slashes in the same path causes issues on Windows, which likes to use \ or // instead of /. I'm not certain why this error is coming up in the latest versions but wasn't an issue in the past.

Bafflingly, if I take that code and try to run it again while changing nothing, I get an entirely different error:

```
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-3-4acfd8f66a0a> in <module>
      4 gaia = 6609630523067800192
      5 
----> 6 star = eleanor.multi_sectors(sectors='all',tic=0,gaia=gaia,coords=(ra,dec),tc=True)

~\anaconda3\envs\lightcurve\lib\site-packages\eleanor-2.0.1-py3.7.egg\eleanor\source.py in multi_sectors(sectors, tic, gaia, coords, name, tc, local, post_dir, pm_dir, metadata_path, tesscut_size)
     74         for s in sectors:
     75             star = Source(tic=tic, gaia=gaia, coords=coords, sector=int(s), tc=tc, local=local, post_dir=post_dir, pm_dir=pm_dir,
---> 76                           metadata_path=metadata_path, tesscut_size=tesscut_size)
     77             if star.sector is not None:
     78                 objs.append(star)

~\anaconda3\envs\lightcurve\lib\site-packages\eleanor-2.0.1-py3.7.egg\eleanor\source.py in __init__(self, tic, gaia, coords, name, fn, sector, fn_dir, tc, local, post_dir, pm_dir, metadata_path, tesscut_size)
    255 
    256             if not os.path.isdir(self.metadata_path + '/metadata/s{:04d}'.format(self.sector)):
--> 257                 Update(sector=self.sector)
    258 
    259             if tc == False:

~\anaconda3\envs\lightcurve\lib\site-packages\eleanor-2.0.1-py3.7.egg\eleanor\update.py in __init__(self, sector)
    128         # memmap=False as wokaround for https://github.com/afeinstein20/eleanor/issues/204
    129         self.cutout = fits.open(manifest['Local Path'][0], memmap=False)
--> 130         os.remove(manifest['Local Path'][0])
    131 
    132 

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '.\\tess-s0002-4-1_68.959708_-64.027036_31x31_astrocut.fits'
```

Now, this one is a bit more baffling to me. I'm no computer expert, but I'm happy to help out with testing on Windows machines, as this is my primary computer for doing astro work.

**Comment by benmontet** [comment]
Hey,

Windows issues take us longer to debug since we don't have any to test on, so we'll rely on users like you to help. 

The first time you're running it, it fails to find `~/.eleanor/metadata/s0002/cadences_s0002.txt`. Can you verify that file exists? If not, try deleting the entire s0002 directory and running again, it should re-calculate everything and put it there if that location doesn't exist.

The second time you're running it, it's getting caught on the 'update' script, which is the one that populates all those metadata folders if they don't exist. So either it's trying to remake the s0002 folder, or made it through that one and is getting stuck in a different sector. I see you're using `eleanor.multi_sectors`. Assuming you know what sectors your target was observed in (and if you don't, you can use `tess-point` to figure it out, or let me know the TIC ID or RA/Dec and I can look it up), can you try running just one sector at a time with the eleanor.Source()/eleanor.TargetData() methods and see if you get a failure in *every* sector or if some sectors work fine and others do not, which would suggest it's a file i/o issue in the metadata?

Thanks!

**Comment by AlexanderEvitt** [comment]
If I try deleting that directory and re-running, I get the error I get the second time. Looks like the second error is the real problematic one.  I tried calling eleanor.Update() for all sectors:
```
for sector in range(30):
    eleanor.Update(sector)
```
But this too ran into problems.
![image](https://user-images.githubusercontent.com/50218791/106190184-4b76a000-6177-11eb-9806-7ca183f7f3ee.png)
I'm not a hundred percent sure exactly what is happening here, but I get the feeling that it downloads the file and then tries to access it again, but cannot because it hasn't stopped using it from the download process. This is definitely a windows-specific thing, if true. Eleanor seems to be downloading these files to the local folder instead of ~/.eleanor.

**Comment by benmontet** [comment]
Ah yes, I see what's happening. It's downloading a file that it only uses temporarily inside the update script to get some other data, and then deletes it. This `os.remove` is the delete step, I moved it around so that the `os.remove` is after the explicit call that closes that file after it's done being used for the last time, I guess unix and windows systems handle the logic around the way it's stored in memory differently.

This hasn't flowed down into the pypi version yet but it's in the github version, so please either download the latest version from here, or update your local update.py file in your `eleanor.__path__` directory to be the version on github instead of the one you already have, and let me know if that fixes the issue.

**Comment by AlexanderEvitt** [comment]
It looks like that pretty much resolved the issue. Thanks for spending your time fixing these bugs.
