### ISSUE TITLE
First-time user problems (installing, dependencies, updates, quick start tutorial)

### ISSUE THREAD

**Issue by MNGuenther** [afeinstein20/eleanor#227]
Hi Adina et al.!

First-time eleanor user here! So the problems I'm facing might just be me, but please point me in the right direction :)
 
- I created a fresh conda environment with python 3.8.5. The way of pip installing eleanor did not work for me, as it would always install eleanor version 0.0.1, even though it iterates over all available versions. Even passing the -U command or exact version number did not work. I bypassed this for now using git clone and setup.py.

- The above way, I also got the famous "tensorflow v2" error. I seem to not be able to solve this because any variation of "pip install tensorflow==1.15.5" results in "ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.5" (even though it exists on PyPi, see: https://pypi.org/project/tensorflow/1.15.5/#history)

- I still went ahead and tried the eleanor.Update(sector=i) step, for which I wrote a one-liner to iterate over all i (is there a prefered build-in .Update_all or .Initialize function?). It worked well (despite no tensorflow) for half the Sectors. However, it crashed for Sectors 2, 5, 6, 8, 10, 12, 13, 15, 16, 19, 20, 23, 24, 26, and couldn't download the data for those. An example error from Sector 2:
```
/tesscut_20210225173306.zip ... [Done]
Inflating...
This is the first light curve you have made for this sector. Getting eleanor metadata products for Sector  2...
This will only take a minute and only needs to be done once. Any other light curves you make in this sector will be faster.
Acquiring target...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Calculating Cadences...
Assuring Quality Flags...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mx/Dropbox (MIT)/Science/Code/eleanor/eleanor/update.py", line 146, in __init__
    self.get_quality()
  File "/Users/mx/Dropbox (MIT)/Science/Code/eleanor/eleanor/update.py", line 283, in get_quality
    twoMin     = fits.open(shortCad_fn)
  File "/Users/mx/opt/anaconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/Users/mx/opt/anaconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 401, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/Users/mx/opt/anaconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1086, in _readfrom
    raise OSError('Empty or corrupt FITS file')
OSError: Empty or corrupt FITS file
```

- lastly, I tried the quick start example for WASP-100 and got the following error (maybe related to my lack of tensorflow?):
```
>>> star = eleanor.Source(tic=38846515, sector=1)
/Users/mx/Dropbox (MIT)/Science/Code/eleanor/eleanor/ffi.py:40: UserWarning: couldn't find pointing model
  warnings.warn("couldn't find pointing model")
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0001/4-1/hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc.fits to ./mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc.fits ...
|=======================================================================================================| 158M/158M (100.00%)      1m 3s
/Users/mx/Dropbox (MIT)/Science/Code/eleanor/eleanor/ffi.py:40: UserWarning: couldn't find pointing model
  warnings.warn("couldn't find pointing model")
```

Thanks so much in advance and hopefully I'll get it running soon with your help :)
Max

**Comment by MNGuenther** [comment]
For future reference, my final way around it:

- fresh conda environment with python=3.6, scipy, numpy, pandas, astropy
- pip install tensorflow==1.15
- pip install eleanor

(all that only works for python<=3.6 for me -- maybe you could make this a big banner/requirement on the installation page?)

Now I can make awesome FFI light curves :)

**Comment by benmontet** [comment]
Hey, 

Welcome aboard! 

You're correct about tensorflow, we require a version <2.0 and the last python version with a 1.1x version is 3.7, so that bit will be incompatible with python 3.8. We'll get to the point where tensorflow is no longer used! There is a branch on the 'hub that mostly is at that point, but it hasn't quite reached the point to be ported over into the main branch. The upshot: the only place tensorflow is used is the psf modeling routines, so if you don't want to make a PSF light curve you can just skip the tensorflow installation and everything else will work just fine, at least in principle. (I think the PSF light curves are usually worth it though! 😉)

To run update for all sectors there is an eleanor.Update.update_all() function, which essentially does the same as the function you wrote. Sounds like you're all set now, but you'll be ready for next time!

Your third issue is interesting to me, I've never seen that before. It's almost but not quite failing on every other sector. I wonder if something too cute is going on behind the scenes? Each sector it downloads some data from MAST needed to make all the metadata files, does some work with them, and then deletes those files. I wonder if your loop was too efficient and it would start to download the next file before the old one was gone and that was somehow confusing it? We give them standardised names so it might have thought the correct file was there as it was being deleted? But that's just a guess on my part.

Did you have the same issues on python 3.7, or did you go straight to 3.6? I use 3.7 locally and it works fine for me, so I hope it would also work just fine for you there! There shouldn't be any differences that would matter between 3.6 and 3.7, so if you chose the former due to personal preference that's totally fine.

We're ready to help in any issues you run into in making or interpreting light curves!
