### ISSUE TITLE
Sectors 40 and 41

### ISSUE THREAD

**Issue by pavolgaj** [afeinstein20/eleanor#236]
I want to download a light curve from TESS sectors 40 and 41 using eleanor. The target was already observed and TESScut generate the corresponding cutout. But, eleanor show this error: 

`Traceback (most recent call last):`
`  File "ffi_tp.py", line 9, in <module>`
`    star = eleanor.Source(name='Theta Lyrae', sector=41) `
`  File "/usr/local/lib/python3.8/dist-packages/eleanor-2.0.3-py3.8.egg/eleanor/source.py", line 258, in __init__`
`    self.locate_on_tess()`
`  File "/usr/local/lib/python3.8/dist-packages/eleanor-2.0.3-py3.8.egg/eleanor/source.py", line 300, in locate_on_tess`
`    arg = np.argwhere(sectors == self.usr_sec)[0]`
`IndexError: index 0 is out of bounds for axis 0 with size 0`

I used star Theta Lyrae as testing target. Sector 14 where this star was also observed works fine.
I used the latest version of eleanor - just clone from GitHub.

**Comment by benmontet** [comment]
Hi Pavol,

There is a file in your `eleanor.__path__` directory called `maxsector.py` This file tells eleanor to only try to make light curves for sectors less than this sector value rather than wasting time continually searching fields that haven’t been observed yet. It sounds like for some reason this file isn’t getting updated on your machine when you try to run an S40 target. I think there are two options that should make things work for you based on your description:

1) manually update the `maxsector.py` file to have a max sector of 41. 
2) run `eleanor.Update(sector=41)` which produces all of the metadata needed for making light curves for a sector. That code takes about two minutes to run, and it should as the very last step update the maxsector parameter internally in eleanor. 

I think one of those is likely to solve your problem, but if it doesn’t let us know and we can talk through other things to try to get your installation running!

**Comment by pavolgaj** [comment]
I tried both options. Update finished successfully with a message that sector 40/41 is now available. I also can see some files for these sectors in ~/.eleanor/metadata folder. Max sector in maxsector.py file is 41.
But, I still can't get a light curve.

**Comment by pavolgaj** [comment]
You're right!
I was using tess-point v0.5.1. And tess_stars2px gave only sector 14. So, I updated this package to the latest version (0.6.1). It works now.
Thanks!

**Comment by benmontet** [comment]
Excellent! Glad it's working. Good luck! I defintely recommend reading the tutorial on [how to deal with very bright stars](https://adina.feinste.in/eleanor/getting_started/tips_tricks.html#1.6-Saturated-targets) if you haven't yet, and let us know if you run into any trouble along the way.

**Comment by Atousa-Kalantari** [comment]
> Hi Pavol,
> 
> There is a file in your `eleanor.__path__` directory called `maxsector.py` This file tells eleanor to only try to make light curves for sectors less than this sector value rather than wasting time continually searching fields that haven’t been observed yet. It sounds like for some reason this file isn’t getting updated on your machine when you try to run an S40 target. I think there are two options that should make things work for you based on your description:
> 
> 1. manually update the `maxsector.py` file to have a max sector of 41.
> 2. run `eleanor.Update(sector=41)` which produces all of the metadata needed for making light curves for a sector. That code takes about two minutes to run, and it should as the very last step update the maxsector parameter internally in eleanor.
> 
> I think one of those is likely to solve your problem, but if it doesn’t let us know and we can talk through other things to try to get your installation running!



Hi @benmontet ,

Have the same issue. I tried updating my eleanor package and also installed it via git clone, so the maxsector.py was set to 97. However, it still didn’t work for sectors 61 and 64. I also checked tess-point to make sure it was up-to-date, and it was.

Running eleanor.Update(sector=61) does work, but it takes a long time, and it’s difficult to run for all the sectors I need. My targets have no postcards (as indicated when running star = eleanor.Source(coords=coords, sector=61)), so I need to use TESSCut instead. Could the lack of postcards be causing this issue?

Do you know if there is a faster way to handle this that you would recommend?

Thanks in advance!
