### ISSUE TITLE
Save data

### ISSUE THREAD

**Issue by pavolgaj** [afeinstein20/eleanor#237]
There is a bug in saving target data:

`Traceback (most recent call last):`
 ` File "ffi_tp.py", line 31, in <module>`
`    data.save(directory='')`
`  File "/usr/local/lib/python3.8/dist-packages/eleanor-2.0.3-py3.8.egg/eleanor/targetdata.py", line 1422, in save`
`    self.source_info.tic, self.source_info.sector, eleanor.__version__))`
`NameError: name 'eleanor' is not defined`

It can be simply fixed by adding `import eleanor` into the function `save` in `targetdata.py` file.

**Comment by benmontet** [comment]
Weird, thank you for pointing this out! It looks like it got deleted in 02f84e62d806a5d584ee80a19f1fd23cf85bb3f5 and has been floating without that import since then. I've added an import straight into `save` so should work now. It's an easy enough fix that I'm going to assert that I probably did it correctly and am going to close the issue; please re-open if you run into any further troubles with this function!
