### ISSUE TITLE
Possible bug in postcard creation

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#238]
https://github.com/afeinstein20/eleanor/blob/86c2d2e23f48fdb9aef9cf51264b4431aed823de/eleanor/ffi.py#L97-L100

I was diving into other things, but this looks like a potential problem. I think the goal of these lines is to find a place where the time difference is larger than 1 normal cadence and assume that signifies the data gap between orbits in a sector.

However, if there are any dropped cadences or safe modes or anything that happens in the first orbit, even if only for a few cadences, I believe that will trick these lines into thinking that's where the orbit break happens. I'm not sure how much that will matter for the purposes of this function's goal. Do the centroids look very different between orbits and that's why you're splitting them up and doing the outlier identification per orbit? 

Anyway, possible not a huge deal, but figured I'd point it out. I'm unfortunately not sure what the solution is... I'm not sure there's a foolproof way to automatically detect orbits purely based on timestamps (maybe the safest is just assuming the largest data gap is the orbit break? then you're only in trouble if there's a longer safe mode in the first orbit, which I'm not sure has happened).

**Comment by benmontet** [comment]
Hey, thanks for pointing this out! You're totally right. Yeah, the centroids do look different along the two orbits, the pointing is not perfectly repeatable from one orbit to the next, so if you plot the centroids you get a line of points representing one orbit and then another line ~0.05 pix away representing the second orbit. Not a huge difference but enough to matter. Having said that, I haven't made that plot since probably Sector 8 or so and things might look very different these days!

If my interpretation is correct this is only used in the generation of the quality flags, right? So it will produce the data but flag it all as spurious. We do handle it more properly in the targetdata routines:

https://github.com/afeinstein20/eleanor/blob/86c2d2e23f48fdb9aef9cf51264b4431aed823de/eleanor/targetdata.py#L1090-L1093

I think it's sensible to just drop this in there, do you agree? You're right that safe modes longer than the break would be a problem, but if we have those we probably have larger problems with that sector. This will need a re-think from Year 5 if the three downlinks per sector strategy starts being used, but I'm very happy to punt on that one for future us to deal with.

I also don't have a better solution so if you don't see any major regular issues from dropping the targetdata funciton in there I'll make that edit!

**Comment by ethankruse** [comment]
Yep that sounds reasonable to me!
