### ISSUE TITLE
Question about eleanor.Source()

### ISSUE THREAD

**Issue by drewweis** [afeinstein20/eleanor#248]
Whenever I try to use the eleanor.Source() function, it throws a `TypeError: download_cutouts() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given` error. This only seems to occur when the `tc` flag is set to True; when set to False or not set, the function seems to work as intended. Is this a mistake on my part, and how can I fix it??

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/54334710/161455198-2515fc16-f441-4a4b-b920-0205f2c29554.png">

**Comment by benmontet** [comment]
This was just fixed over the weekend in #247 actually; it seems the latest update to astroquery (version 0.4.6) which was just released changed how TessCut needs to be called, which means it throws an error in the way it was called by eleanor. 

You can sort it by cloning and using the latest version of eleanor off of github rather than using the version on pypi, or by downgrading your astroquery one version to 0.4.5. The fix that's currently in the github version will propogate through to the pypi version of eleanor the next time we do a version update, too.

**Comment by drewweis** [comment]
That fixed it. Thank you so much!
