### ISSUE TITLE
Quickstart example fails

### ISSUE THREAD

**Issue by MrBudgens** [afeinstein20/eleanor#78]
Running through the quickstart example fails when eleanor.TargetData() is called, throwing an IndexError. Line 197 of postcard.py is trying to access index [4], whereas the postcard fits file that has been downloaded only has entries up to [3] when opened using astropy.io.fits.

My installation was by cloning from github and running setup.py on python 3.7.3 (pip install was not an option on my local machine - see the other issue I have just opened). The offending line appears not to exist in the version that pip installs (which I have managed to do on an inconveniently remote linux server running python 3.6.8)

**Comment by afeinstein20** [comment]
Hi @MrBudgens, thank you for bringing this to our attention! The version we currently have on Github is using a new postcard format that we are beta testing, which is why you are running into the index accessing issue. If you clone this version, it should work properly: https://github.com/afeinstein20/eleanor/tree/20cc27a446eea863e60811b85b6039b3e1b1752d

Let me know if you have any issues!
