### ISSUE TITLE
Splitting project into two repos?

### ISSUE THREAD

**Issue by dfm** [afeinstein20/eleanor#99]
Hey team, what do you think about also splitting the `make_*` scripts into a separate repo (that perhaps depends on the main eleanor repo). This would be nice because then not every user would need to compile the new interpolation routine (only if they want to generate the data files) and I think it might be easier to maintain. We could call it `eleanor-tools` or something... What do y'all think of that? If you agree that that could be a good idea, I'm happy to do it and then transfer ownership of the repo back to you @afeinstein20.

**Comment by benmontet** [comment]
I have no issues with this!

**Comment by afeinstein20** [comment]
Sounds fine to me!

**Comment by dfm** [comment]
OK - I create a new repo and just transferred ownership to you, @afeinstein20. Can you add me as a collaborator on that repo when you accept the transfer?

Also: it seems like the guide script no longer works as before - what's needed with that?

**Comment by afeinstein20** [comment]
Accepted and it says you're already a collaborator! 

I'm not sure what happened to the guide script. I think there might be a way to use [tess-point](https://github.com/christopherburke/tess-point/blob/master/tess_stars2px.py) instead of having the guide altogether. Do you need it to run the postcards right now?

**Comment by benmontet** [comment]
Which script, make_guide or something downstream that uses the guide? Adina
re-wrote the guide script at some point because we realized we can build a
much more efficient guide, since the postcard grid is the same in each
camera chip (we never have to figure out where the boundaries are on the
postcards, once we know the detector coordinates we automatically know what
postcard we should be on). I don't know what would have happened to
make_guide though, if anything, if that's where the issue is!

**Comment by dfm** [comment]
Ah - so you mean that you don't need the postcard.guide files anymore? I was wondering whether or not I needed to still generate those and I found that there was no code to do it anymore :)

**Comment by benmontet** [comment]
Okay, thinking through this, I think the answer is no, at least not the way
we've been doing it. Adina, please correct me if what I say is wrong or you
think this is a bad approach.

We can use all of the functions we have to get the coordinates. I don't
know how thoroughly we can trust tess-point to give us the correct position
to 1-pixel accuracy for all sectors. But if we had a guide that had just
the information needed to produce a WCS solution---so one entry per
camera/chip set, not one entry per postcard, we can loop through that,
figure out what camera/chip/sector its on, and what pixel on that camera
chip from the WCS, and then we uniquely know what the best postcard is,
because we know exactly what the postcard grid looks like.

Adina, does that sound like a good path to you?

It looks like make_guide returns a file called ffi.guide, but I didn't look
closely enough to see if that is what it is doing now or not.

I will look at the background this afternoon and try to figure out why
yours is different than mine, but I'm presenting at journal club in 90
minutes and need to read the paper for that first!

**Comment by afeinstein20** [comment]
I think that's reasonable. The other thing we can do now is streamline how quickly it looks through the guide because tess-point does give sector-camera-chip. Right now it still does loop through every postcard header. This should be relatively straightforward to fix as the postcards are created at fixed locations. I can work on why make_guide.py isn't working anymore, fixing the format, and also incorporating this into source.locate_on_tess().
